/**
 * One-off helper to generate fixtures/sample-import.xlsx for local preview testing.
 * Does not touch the database.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import * as XLSX from "xlsx";

const headers = [
  "Business Name",
  "Category",
  "Area",
  "Address",
  "Phone",
  "International Phone",
  "Website",
  "Has Website",
  "Social Platform",
  "Social Link",
  "Google Rating",
  "Review Count",
  "Google Maps Link",
  "Place ID",
  "Source Keyword",
  "Website Quality Notes",
  "Suitable Lead",
  "Lead Status",
  "Priority",
  "Manual Notes",
  "Contacted",
  "Response",
  "Follow Up Date",
  "New / Existing Lead",
  "Created At",
];

const rows: string[][] = [
  headers,
  [
    "Zen Ear Studio 采耳",
    "beauty_salon",
    "Austin",
    "1 Main St",
    "+15125550123",
    "",
    "https://zen.example",
    "Yes",
    "Instagram",
    "https://instagram.com/zenear",
    "4.8",
    "120",
    "https://maps.google.com/?q=1",
    "ChIJsample1",
    "采耳 Austin",
    "",
    "Yes",
    "New",
    "High",
    "",
    "No",
    "",
    "",
    "New",
    "2026-01-01",
  ],
  [
    "Glow Spa",
    "spa",
    "Austin",
    "2 Oak Ave",
    "",
    "",
    "https://glow.example",
    "Yes",
    "",
    "",
    "4.5",
    "10",
    "",
    "",
    "spa deals",
    "",
    "Yes",
    "New",
    "Normal",
    "",
    "No",
    "",
    "",
    "New",
    "2026-01-02",
  ],
  [
    "No Web Nail",
    "nail_salon",
    "Dallas",
    "3 Elm",
    "",
    "",
    "",
    "No",
    "Facebook",
    "https://facebook.com/noweb",
    "4.0",
    "5",
    "",
    "ChIJsample2",
    "nails Dallas",
    "",
    "No",
    "New",
    "Normal",
    "",
    "No",
    "",
    "",
    "New",
    "2026-01-03",
  ],
  [
    "Earpro Clinic",
    "health",
    "Houston",
    "4 Pine",
    "",
    "+12835551234",
    "",
    "No",
    "",
    "",
    "4.2",
    "40",
    "",
    "",
    "ear care",
    "",
    "Yes",
    "New",
    "Low",
    "",
    "No",
    "",
    "",
    "New",
    "2026-01-04",
  ],
  [
    "Low Signal Shop",
    "retail",
    "Austin",
    "5 Cedar",
    "",
    "",
    "",
    "No",
    "",
    "",
    "3.0",
    "2",
    "",
    "",
    "retail",
    "",
    "No",
    "New",
    "Normal",
    "",
    "No",
    "",
    "",
    "New",
    "2026-01-05",
  ],
];

const outDir = path.join(__dirname, "..", "fixtures");
const outFile = path.join(outDir, "sample-import.xlsx");

fs.mkdirSync(outDir, { recursive: true });
const wb = XLSX.utils.book_new();
const ws = XLSX.utils.aoa_to_sheet(rows);
XLSX.utils.book_append_sheet(wb, ws, "Leads");
XLSX.writeFile(wb, outFile);
console.log("Wrote", outFile);
